### DISCUSSION TITLE
Custom quick-start startup parameters

### DISCUSSION THREAD

**Discussion by JacieChao** [cnrancher/autok3s#570] [Ideas]
All quickstart parameters for each provider are built-in provider codes and users can't customize the parameters unless creating a default cluster template(but the templates are not supported for CLI). It's not friendly to update built-in parameters to support the best configuration practices for different cloud users.

https://github.com/cnrancher/autok3s/issues/268

## Design

Using a configuration file to save the built-in parameters instead of declaring them in codes. Users can edit or replace the configuration file to change the default parameters.

The startup parameters template is YAML type and the following is an example.

```
aws:
  ami: "ami-06878d265978313ca"
  instance-type: "t3a.medium"
  volume-type: "gp3"
  root-size: "16"
  region: "us-east-1"
  zone: "us-east-1a"
  request-spot-instance: false
  cloud-controller-manager: false
alibaba:
  image: "ubuntu_22_04_x64_20G_alibase_20221130.vhd"
  instance-type: "ecs.s6-c1m2.large"
  internet-max-bandwidth-out: "5"
  disk-category: "cloud_essd"
  disk-size: "40"
  eip: false
  cloud-controller-manager: false
  region: "cn-hangzhou"
  zone: "cn-hangzhou-i"
  spot-strategy: "NoSpot"
  spot-duration: 1
```

AutoK3s will use the built-in parameters and users can replace the default parameters by setting the environment 
 value for `AUTOK3S_PROVIDER_TEMPLATES`, e.g. `AUTOK3S_PROVIDER_TEMPLATES=/myautok3s/templates.yaml`. 

There's no restriction for users to customize parameters for all kinds of providers. It's available to set parameter templates for only one provider which is used frequently.

After customizing the default parameters, it's available for users to create a cluster by the following CLI
```
autok3s create -p aws --name myk3s --master 1 --worker 1
```

AutoK3s CLI supports using CLI parameters and environment variables to pass in provider options. The priority order of parameter settings is: `CLI parameters` > `environment variables` > `default startup parameters`
