### ISSUE TITLE
Support Pass Private Registry Configuration From CLI

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#162]
```
--registry /etc/autok3s/registries.yaml

# registries.yaml
mirrors:
  docker.io:
    endpoint:
      - "https://mycustomreg.com:5000"
configs:
  "mycustomreg:5000":
    auth:
      username: xxxxxx # this is the registry username
      password: xxxxxx # this is the registry password
    tls:
      cert_file: # path to the cert file used in the registry
      key_file:  # path to the key file used in the registry
      ca_file:   # path to the ca file used in the registry
```
