### ISSUE TITLE
[BUG] docker-compose - windows - Cannot connect to the Docker daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by doublefx** [cnrancher/autok3s#524]
**Describe the bug**
Not sure whether it is a missconfiguration or a bug

**To reproduce**
1. Create a docker-compose.yaml:
``` yaml
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  autok3s:
    image: cnrancher/autok3s:v0.6.0
    init: true
    ports:
    - 8080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - C:\\Users\\doublefx\\.autok3s\\:/home/.autok3s/
    environment:
    - AUTOK3S_CONFIG=/home/.autok3s/
    - VIRTUAL_HOST=autok3s.vcap.me
```
2. run docker-compose -d up
3. create a k3d cluster
4. See an error: `Cannot connect to the Docker daemon at unix:///var/run/docker.sock`

![image](https://user-images.githubusercontent.com/1222171/201648992-1aaeedcd-72af-4c0c-8ccf-e66bf9e146cc.png)

OS: Windows 11
AutoK3s Version: [v0.6.0](https://github.com/cnrancher/autok3s/releases/tag/v0.6.0)

**Comment by Jason-ZW** [comment]
@doublefx Thanks for your feedback!

Try change the volume mounts path `/var/run/docker.sock:/var/run/docker.sock:ro` like this:


```
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  autok3s:
    image: cnrancher/autok3s:v0.6.0
    init: true
    ports:
    - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - C:\\Users\\doublefx\\.autok3s\\:/home/.autok3s/
    environment:
    - AUTOK3S_CONFIG=/home/.autok3s/
    - VIRTUAL_HOST=autok3s.vcap.me
```

**Comment by doublefx** [comment]
I tried but it failed to start the ngnix service.

Weirdly, when using `/tmp/docker.sock` and connecting to  Container autok3s-autok3s-1, then running:

`curl --unix-socket /tmp/docker.sock http://0.0.0.0/version`

It works:

``` json
{"Platform":{"Name":"Docker Desktop 4.13.1 (90346)"},"Components":[{"Name":"Engine","Version":"20.10.20","Details":{"ApiVersion":"1.41","Arch":"amd64","BuildTime":"2022-10-18T18:18:35.000000000+00:00","Experimental":"false","GitCommit":"03df974","GoVersion":"go1.18.7","KernelVersion":"5.15.68.1-microsoft-standard-WSL2","MinAPIVersion":"1.12","Os":"linux"}},{"Name":"containerd","Version":"1.6.8","Details":{"GitCommit":"9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6"}},{"Name":"runc","Version":"1.1.4","Details":{"GitCommit":"v1.1.4-0-g5fd4c4d"}},{"Name":"docker-init","Version":"0.19.0","Details":{"GitCommit":"de40ad0"}}],"Version":"20.10.20","ApiVersion":"1.41","MinAPIVersion":"1.12","GitCommit":"03df974","GoVersion":"go1.18.7","Os":"linux","Arch":"amd64","KernelVersion":"5.15.68.1-microsoft-standard-WSL2","BuildTime":"2022-10-18T18:18:35.000000000+00:00"}
```

**Comment by Jason-ZW** [comment]
This should be a bug in `k3d` provider. Only the default socket path is considered here, and the custom `DOCKER_HOST` env is not open to configure.
You can try to use the `autok3s -d serve` command to get it up and running.

**Comment by doublefx** [comment]
If you mean from directly from the CLI, see [my other issue](https://github.com/cnrancher/autok3s/issues/523)

**Comment by Jason-ZW** [comment]
Try this docker compose(which only running autok3s container with host port mapping), then access ui using `http://127.0.0.1:<host mapping>`:
```
services:
  autok3s:
    image: cnrancher/autok3s:v0.6.0
    init: true
    ports:
    - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/.autok3s/:$HOME/.autok3s/
    environment:
    - AUTOK3S_CONFIG=$HOME/.autok3s/
```

**Comment by doublefx** [comment]
Yes, got it working with:

``` yaml
services:
  autok3s:
    image: cnrancher/autok3s:v0.6.0
    init: true
    ports:
    - 80:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/.autok3s/:/home/.autok3s/
    environment:
    - AUTOK3S_CONFIG=/home/.autok3s/
```

Do you know any other way to get a virtual host on the top?

**Comment by doublefx** [comment]
All right, a bit better:

``` yaml
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  autok3s:
    image: cnrancher/autok3s:v0.6.0
    init: true
    ports:
    - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/.autok3s/:/home/.autok3s/
    environment:
    - AUTOK3S_CONFIG=/home/.autok3s/
    - VIRTUAL_HOST=autok3s.vcap.me
```

Which allow to connect to autok3s.vcap.me and create a cluster **but unfortunately the cluster does not appear in the UI**.

![image](https://user-images.githubusercontent.com/1222171/201674810-b9c369d9-6ea9-45ee-b3f7-8aa9eb9ebead.png)

But it still created:

![image](https://user-images.githubusercontent.com/1222171/201674928-da376862-42f9-4188-8d7a-2862dc8c0458.png)

**Comment by Jason-ZW** [comment]
I will support enviroment `DOCKER_SOCKET` feature as soon as possible to support this scenario.

**Comment by doublefx** [comment]
Yes please as not having the cluster in the UI, I cannot do any action on it (Delete, Clone, ...)

**Comment by doublefx** [comment]
Also, I wonder if it has some connectivity consequences as none of the create pods succeeded, see FailedCreatePodSandBox in the above log, what do you think?

**Comment by Jason-ZW** [comment]
Can your environment access the Internet?
I try on my environment and the pods can be pulled down.

Unfortunately I think `0.6.0` is a failed version, it is recommended to use 0.5.2 to experience.

**Comment by doublefx** [comment]
I can manually `curl https://auth.docker.io/token?scope=repository%3Arancher%2Fpause%3Apull&service=registry.docker.io` from inside the cluster

**Comment by Jason-ZW** [comment]
I will try your steps on windows tomorrow, then give your feedback message.

**Comment by Jason-ZW** [comment]
@doublefx Using Windows 11 22H2 can not reproduce your situation.

```
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  autok3s:
    image: cnrancher/autok3s:v0.6.0
    init: true
    ports:
    - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/.autok3s/:/home/.autok3s/
    environment:
    - AUTOK3S_CONFIG=/home/.autok3s/
    - VIRTUAL_HOST=autok3s.vcap.me
```

<img width="740" alt="image" src="https://user-images.githubusercontent.com/36479205/201902585-a6cdc223-16aa-4a6b-a5b8-be7ac29a072f.png">
