### ISSUE TITLE
help: Does autok3s support distributing custom `registries.yaml` to nodes

### ISSUE THREAD

**Issue by jinjianming** [cnrancher/autok3s#588]
hello @orangedeng  autok3s Does support  Customize content distribution to`/etc/rancher/k3s/registries.yaml`
```
mirrors:
  docker.io:
    endpoint:
      - "https://mycustomreg.com:5000"
configs:
  "mycustomreg:5000":
    auth:
      username: xxxxxx # 这是私有镜像仓库的用户名
      password: xxxxxx # 这是私有镜像仓库的密码
    tls:
      cert_file: # 镜像仓库中使用的cert文件的路径。
      key_file:  # 镜像仓库中使用的key文件的路径。
      ca_file:   # 镜像仓库中使用的ca文件的路径。
```

**I saw the `--registry /etc/autok3s/registries.yaml` parameter. Will this be distributed to other hosts**
